micronaut:
    application:
        name: micro

# H2 Database
datasources:
    default:
        # needs to be escaped with backticks
        url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
        username: ${JDBC_USER:sa}
        password: ${JDBC_PASSWORD:""}
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
    default:
        packages-to-scan:
            - 'cberry.dev'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true

database:
    max: 50